---
abstract: 'Base class for representing documents'
author:
  - 'Project Renard'
build_requires:
  Test::Most: '0'
  lib: '0'
  perl: '5.010'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.010'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Renard-Incunabula-Document
requires:
  Module::Load: '0'
  Moo: '0'
  Moo::Role: '0'
  MooX::Lsub: '0'
  Renard::Incunabula::Common::Setup: '0'
  Renard::Incunabula::Common::Types: '0'
  Type::Library: '0.008'
  Type::Utils: '0'
  Types::Common::Numeric: '0'
  autovivification: '0'
  perl: '5.010'
resources:
  homepage: https://github.com/project-renard/p5-Renard-Incunabula-Document
  repository: https://github.com/project-renard/p5-Renard-Incunabula-Document.git
version: '0.004'
x_serialization_backend: 'YAML::Tiny version 1.70'
